source 'https://rubygems.org'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'monban'
gem 'pg'
gem 'pry-rails'
gem 'rails', '4.1.6'
gem 'rake'
gem 'rubocop'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'spring'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
