source 'https://rubygems.org'
gem 'better_errors'
gem 'bookings'
gem 'coffee-rails', '~> 4.0.0'
gem 'database_cleaner'
gem 'factory_girl_rails'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'launchy'
gem 'monban'
gem 'puma'
gem 'pry-rails'
gem 'rails', '4.1.6'
gem 'rspec-rails'
gem 'rubocop'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'shoulda-matchers'
gem 'sqlite3'
gem 'spring'
gem 'suspenders'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
end
