default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  development:
  <<: *default
  database: lets_meet_development

test:
  <<: *default
  database: lets_meet_test

production:
  <<: *default
  database: lets_meet_production
  username: lets_meet
  password: <%= ENV['LETS_MEET_DATABASE_PASSWORD'] %>
